spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: enrollment
    password: enrollment
  jpa:
    show-sql: false
